### ISSUE TITLE
Feature request: Switch file icon themes as well

### ISSUE THREAD

**Issue by neet** [intodevelopment/nightlight#1]
Thanks for keep on developing an awesome plugin. I really love to use it!

There are some icon themes that have light/dark option such as [Material Theme](https://marketplace.visualstudio.com/items?itemName=Equinusocio.vsc-material-theme), so it would be nice if I could switch File Icon Theme as well as Color Theme.

**Comment by intodevelopment** [comment]
Thanks! That's a good idea, I'll look into it and will keep you posted.

**Comment by intodevelopment** [comment]
As of version 1.3 you can also set `nightlight.nightIconTheme` and `nightlight.dayIconTheme` to make the icon theme switch as well.

**Comment by neet** [comment]
Awesome! Thank you🎉
